### ISSUE TITLE
Dependency problem?

### ISSUE THREAD

**Issue by p3v9d5ui** [image-js/fast-png#10]
I installed the latest version of fast-png (4.0.1), and I get the following error:

`TypeError: IOBuffer is not a constructor`

There seems to be some incompatibility between fast-png and the latest version of iobuffer (also 4.0.1), which meets fast-png's dependencies.

I had to downgrade to fast-png@3.1.0, which pulls in iobuffer@3.2.0, and that worked fine.

**Comment by targos** [comment]
Hi, do you have exact steps to reproduce this? From a local test in the Node.js repl it seems to work correctly.

**Comment by p3v9d5ui** [comment]
Hi @targos. No, I don't, unfortunately. I'm using this as part of a larger project, so I guess there is some combination of dependencies that is causing this issue.
