### ISSUE TITLE
JHKAJKH aKShjk aSDHJKasdhjk ads JHKAJKH aKShjk aSDHJKasdhjk ads JHKAJKH aKShjk aSDHJKasdhjk ads JHKAJKH aKShjk aSDHJKasdhjk ads JHKAJKH aKShjk aSDHJKasdhjk ads JHKAJKH aKShjk aSDHJKasdhjk ads #27

### ISSUE THREAD

**Issue by pkrumins** [image-js/fast-png#27]
hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asf̶̻᷈dhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad h̷̺̕jklah jd hjasdfjlkkhj asfdhk jadsfh̷̡̓ kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjk̵͚᷅lah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk ja̸̤᷆dsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jka̴̤︣d hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdh̶̞̚k jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjaś̴̼dh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjkla̶̩︢h jd hjasdfjlkkhj asf̸̗᷉dhk jadsfh kjasdh jkad hjkl̶̰ͮah jd hjasdfjlkk̶̩͠hj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hj̴̅͢klah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hj̸̖̋asdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfḧ̷᷊ kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd h̶̛̳jasdfj̴͈᷅lkkhj asfdhk jadsfh kjasdh j̷̗᷃kad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfj̴̼̈́lkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdf̷̟̚jlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlk̷̳͐khj asfdhk jadsfh kjasdh j̸̪ͮkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfj̶͎ͨlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfj̴᷂᷉lkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hj̶͕̉asdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah̸͈ͯ jd hjasdfjlkkhj asfdhk jadsfh kjasdh jka̵̙᷅d hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkk̴͔̀hj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hja̴̠͋sdfjlkkhj asfdhk jadsfh kjasdh jkad hjkl̵̠̈́ah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jka̶̡͂d hjkla̷̯᷀h jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh j̷͎͗kad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd h̶̦̆jasdfjlkkhj asfdhk jadsfh̷̺͌ kjasdh jkad hjklah jd hjasdfj̷̣̆lkkhj asfdhk̸̭︠ jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh̵̲͆ jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asf̵̱͗dhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkà̴͉d hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad h̷̗ͯjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd hjasdfjlkkhj asfdhk jadsfh kjasdh jkad hjklah jd

**Comment by cAttte** [comment]
what is the point of calling your library "fast" if you won't provide any benchmarks?

**Comment by pkrumins** [comment]
ssh bby is ok
