### ISSUE TITLE
tRNS not handled properly, causing a error during decoding gray scale images.

### ISSUE THREAD

**Issue by blvd20** [image-js/fast-png#31]
https://github.com/image-js/fast-png/blob/9563e3dcc66bd402c3a969dfe1027bf897ab9296/src/PngDecoder.ts#L212

At least, there should have a `this.skip(length)`.

**Comment by targos** [comment]
Can you share an image that causes this issue so we can use it in unit tests?

**Comment by blvd20** [comment]
![914](https://github.com/image-js/fast-png/assets/6908761/040cb042-5620-4676-82cc-9de997a4340d)
@targos

**Comment by targos** [comment]
Thanks. Fixed in version 6.2.0.

The field is now correctly decoded and its values can be read from `img.transparency`.
